440: Remove 'Return To Listing' button from Person#show
ReadyResponder/ReadyResponder pull request #554
Opened 2017-10-13 16:32 UTC by ShadowBan

Fixes: https://github.com/ReadyResponder/ReadyResponder/issues/440

Approach:
  Removed 'Return to Listing' button along with controller actions to keep track of what the button should return you to.  Removed tests that were associated with the 'Return to Listing' button.

2017-10-13 20:18 UTC, kgf commented
@ShadowBan Thanks so much for your interest.
I fear that your efforts were duplicated by @goldenhub77 . I have asked him to provide a review.
Perhaps there is another issue you would like to tackle ?
Thanks again,
Kevin

2017-10-14 03:48 UTC, goldenhub77 requested changes
My prior PR's did not remove this button but did refactor the way referrers are managed. Due to this fact the only change within here that will need to be merged is removing the 'return to listing' button. I will be submitting a PR to do that within a different commit.

2017-10-14 04:03 UTC, goldenhub77 commented
@kgf refer to https://github.com/ReadyResponder/ReadyResponder/pull/558

2017-10-15 13:34 UTC, kgf commented
@ShadowBan Thanks for your contribution. I am closing this un-merged, because it doesn't pass the tests, and it is duplicated by others. I am not marking it as invalid.
I hope that you'll take a look and choose another issue.
Thanks for your help.
Kevin

2017-10-15 13:34 UTC, closed without merging